import { useParams, Link } from 'react-router-dom';
import { useApi } from '../lib/useApi';

interface Line { id: string; description?: string; quantity: string; rate: string; discount: string; taxRate: string; lineTotal: string; item: { sku: string; name: string }; }
interface Invoice {
  id: string; number?: string; date: string; dueDate?: string; status: string;
  subtotal: string; taxTotal: string; total: string; amountPaid: string;
  customer: { name: string; billingAddress?: string; taxId?: string };
  lines: Line[];
}
interface Settings { business: { name: string; currency: string; taxId?: string } | null; }

export default function InvoicePrint() {
  const { id } = useParams();
  const { data: inv } = useApi<Invoice>(`/invoices/${id}`);
  const { data: settings } = useApi<Settings>('/settings');
  if (!inv) return <div className="center muted">Loading…</div>;
  const biz = settings?.business;

  return (
    <div className="print-page">
      <div className="no-print" style={{ marginBottom: 12 }}>
        <Link to="/sales">← Back</Link>
        <button style={{ marginLeft: 16 }} onClick={() => window.print()}>Print / Save PDF</button>
      </div>

      <div className="invoice-paper">
        <div style={{ display: 'flex', justifyContent: 'space-between' }}>
          <div>
            <h1 style={{ margin: 0 }}>{biz?.name ?? 'WorkshopOS'}</h1>
            {biz?.taxId && <div className="muted">Tax ID: {biz.taxId}</div>}
          </div>
          <div style={{ textAlign: 'right' }}>
            <h2 style={{ margin: 0 }}>INVOICE</h2>
            <div><strong>{inv.number ?? '(draft)'}</strong></div>
            <div className="muted">{inv.date.slice(0, 10)}</div>
            <div className="muted">Status: {inv.status}</div>
          </div>
        </div>

        <div style={{ marginTop: 24 }}>
          <div className="muted">Bill to</div>
          <div><strong>{inv.customer.name}</strong></div>
          {inv.customer.billingAddress && <div>{inv.customer.billingAddress}</div>}
          {inv.customer.taxId && <div className="muted">Tax ID: {inv.customer.taxId}</div>}
        </div>

        <table style={{ marginTop: 20 }}>
          <thead>
            <tr><th>Item</th><th className="num">Qty</th><th className="num">Rate</th><th className="num">Disc</th><th className="num">Tax %</th><th className="num">Amount</th></tr>
          </thead>
          <tbody>
            {inv.lines.map((l) => (
              <tr key={l.id}>
                <td>{l.item.sku} {l.item.name}{l.description ? ` — ${l.description}` : ''}</td>
                <td className="num">{l.quantity}</td>
                <td className="num">{l.rate}</td>
                <td className="num">{l.discount}</td>
                <td className="num">{l.taxRate}</td>
                <td className="num">{l.lineTotal}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 16 }}>
          <table style={{ width: 280 }}>
            <tbody>
              <tr><td>Subtotal</td><td className="num">{inv.subtotal}</td></tr>
              <tr><td>Tax</td><td className="num">{inv.taxTotal}</td></tr>
              <tr style={{ fontWeight: 700 }}><td>Total ({biz?.currency})</td><td className="num">{inv.total}</td></tr>
              <tr><td>Paid</td><td className="num">{inv.amountPaid}</td></tr>
              <tr style={{ fontWeight: 700 }}><td>Balance due</td><td className="num">{(Number(inv.total) - Number(inv.amountPaid)).toFixed(2)}</td></tr>
            </tbody>
          </table>
        </div>

        <p className="muted" style={{ marginTop: 40, fontSize: 12 }}>Generated by WorkshopOS</p>
      </div>
    </div>
  );
}
